version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: vimo
      POSTGRES_USER: vimo_user
      POSTGRES_PASSWORD: vimo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vimo_user -d vimo"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./back
    container_name: vimo_backend
    restart: always
    environment:
      POSTGRES_DB: vimo
      POSTGRES_USER: vimo_user
      POSTGRES_PASSWORD: vimo_pass
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "echo 'Waiting for DB...' && \
      while ! nc -z db 5432; do sleep 0.2; done; \
      echo 'Database is up!' && \
      python manage.py migrate --noinput && \
      python manage.py runserver 0.0.0.0:8000"

volumes:
  postgres_data:
